### PR TITLE
remove envs dependency from server index

### PR DESCRIPTION
**Pull request by vdegenne**

### CODE REVIEW

**Comment by vdegenne** [comment]
The reason for that is the environment should probably be in `api` package because that's where the keys belong to.

**Comment by VandeurenGlenn** [comment]
> The reason for that is the env vars should probably be in `api` package because that's where the keys belong to.

Yes, was going to say the same, I'm not comfortable it being in server exports 📦

**Comment by vdegenne** [comment]
@VandeurenGlenn Or even better, maybe we should put the `.env` file at the root of the project. so for example server can use the port, and api the keys, etc.

**Comment by vdegenne** [comment]
If we do that we should probably make a `env` package too :eyes:

**Comment by vdegenne** [comment]
@VandeurenGlenn check that https://github.com/VandeurenGlenn/blue_server/pull/12

**Comment by vdegenne** [comment]
Let's just close this branch, it's f*cked

**Pull request closed without merging**
