### PR TITLE
Fix server

### PR DESCRIPTION
**Pull request by VandeurenGlenn**

### CODE REVIEW

**Review by vdegenne — COMMENTED** [review]
@VandeurenGlenn I trust you on this one, LGTM. Try to remove these changes in the `server-port` branch to avoid conflict?

**Review by vdegenne — APPROVED** [review]

**Comment by VandeurenGlenn** [comment]
> @VandeurenGlenn I trust you on this one, LGTM. Try to remove these changes in the `server-port` branch to avoid conflict?

I'll prob just close this PR and just do yours

**Comment by vdegenne** [comment]
> > @VandeurenGlenn I trust you on this one, LGTM. Try to remove these changes in the `server-port` branch to avoid conflict?
> 
> I'll prob just close this PR and just do yours

Why? you made some good changes there

**Comment by VandeurenGlenn** [comment]
> > > @VandeurenGlenn I trust you on this one, LGTM. Try to remove these changes in the `server-port` branch to avoid conflict?
> > 
> > 
> > I'll prob just close this PR and just do yours
> 
> Why? you made some good changes there

So I didn't see your other PR, it's merged Ill rebase mine to main

**Comment by vdegenne** [comment]
- OK - !

**Pull request merged**
