### PR TITLE
add github and coinmarketcap to exports list

### PR DESCRIPTION
**Pull request by vdegenne**

### CODE REVIEW

**Comment by VandeurenGlenn** [comment]
@vdegenne Why you want them in exports?

**Comment by vdegenne** [comment]
@VandeurenGlenn I'm using them in the front

**Comment by VandeurenGlenn** [comment]
> @VandeurenGlenn I'm using them in the front

But then why we have a server?

**Comment by vdegenne** [comment]
> > @VandeurenGlenn I'm using them in the front
> 
> But then why we have a server?

Im just building a static list with asset information so you can reduce the amount of data the server send to front. This way I can just "connect" the id to this static list to retrieve information like description etc

**Comment by VandeurenGlenn** [comment]
@vdegenne if we do that the app will be down in minutes, especially if people actually use it

**Comment by vdegenne** [comment]
@VandeurenGlenn Please read my last comment...

**Comment by VandeurenGlenn** [comment]
> > > @VandeurenGlenn I'm using them in the front
> > 
> > 
> > But then why we have a server?
> 
> Im just building a static list with asset information so you can reduce the amount of data the server send to front. This way I can just "connect" the id to this static list to retrieve information like description etc

That's not gonna work top 100 changes daily to hourly so gonna end with lot of storage not needed

**Comment by vdegenne** [comment]
> > > > @VandeurenGlenn I'm using them in the front
> > > 
> > > 
> > > But then why we have a server?
> > 
> > 
> > Im just building a static list with asset information so you can reduce the amount of data the server send to front. This way I can just "connect" the id to this static list to retrieve information like description etc
> 
> That's not gonna work top 100 changes daily to hourly so gonna end with lot of storage not needed

Nah I will include like top 120 on a weekly basis just to be sure I have basic information. Things like description, slug etc, don't change daily.

**Review by VandeurenGlenn — APPROVED** [review]

**Pull request merged**
